plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'androidx.baselineprofile'
}

android {
    namespace 'com.zenith.thermal'
    compileSdk 35
    aaptOptions {
        noCompress 'zenithd', 'profiles.json'
    }

    defaultConfig {
        applicationId 'com.zenith.thermal'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions { jvmTarget = '1.8' }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.profileinstaller:profileinstaller:1.4.1'

    def composeBom = platform('androidx.compose:compose-bom:2024.04.01')
    implementation composeBom

    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.activity:activity-compose:1.9.1'
    implementation 'androidx.navigation:navigation-compose:2.7.7'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose:2.8.0'
}
